# Database persistence type.
conductor.db.type=postgres
conductor.queue.type=postgres
conductor.external-payload-storage.type=postgres

# Database connectivity
spring.datasource.url=jdbc:postgresql://10.55.0.13:5432/oss_conductor
spring.datasource.username=oss_conductor_ed7vc44x6e
spring.datasource.password=h3BB9Mt4skEXy6qkkkahO54IAtXUNWNNfOKCimJB

# Indexing Properties
conductor.indexing.enabled=true
conductor.elasticsearch.url=https://tld-stg-us-west1.es.us-west1.gcp.cloud.es.io
conductor.elasticsearch.username=elastic
conductor.elasticsearch.password=rdN9pWGrhjqEckhwO8CRZ885
conductor.elasticsearch.indexName=oss_conductor
conductor.elasticsearch.version=7
conductor.elasticsearch.clusterHealthColor=yellow

# Additional modules for metrics collection exposed to Prometheus (optional)
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

# Load sample kitchen-sink workflow
loadSample=false


# internal conductor properties
# conductor.app.systemTaskWorkerCallbackDuration="5s"